### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wolfv** [comment]
I think we need C++ 17 for the windows build to have std::string_view

**Comment by xhochy** [comment]
> I think we need C++ 17 for the windows build to have std::string_view

That should be possible with a bit of tweaking in the configure.win script

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by marimeireles** [comment]
> That should be possible with a bit of tweaking in the configure.win script

You mean changing this file: `azure-pipelines-win.yml`?
I looked around a bit and couldn't find any docs or examples on how to do this. Do you have any pointer @xhochy ?
Thanks :)

**Comment by xhochy** [comment]
Pushed what I mean. This gets us a bit further but there are things in Rcpp that seem to be removed in C++17.

**Pull request closed without merging**
